# Generated by Django 3.1.7 on 2021-03-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_page.content_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ('order',),
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Текстовый блок',
                'verbose_name_plural': 'Текстовые блоки',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.content')),
                ('audio_bitrate', models.PositiveIntegerField(default=320, verbose_name='Битрейт')),
            ],
            options={
                'verbose_name': 'Аудио блок',
                'verbose_name_plural': 'Аудио блоки',
                'ordering': ('order',),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('page.content',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.content')),
                ('text_field', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текстовый блок',
                'verbose_name_plural': 'Текстовые блоки',
                'ordering': ('order',),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('page.content',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.content')),
                ('video_link', models.URLField(verbose_name='Ссылка на видео файл')),
                ('subtitle_link', models.URLField(verbose_name='Ссылка на субтитры к видео')),
            ],
            options={
                'verbose_name': 'Видео блок',
                'verbose_name_plural': 'Видео блоки',
                'ordering': ('order',),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('page.content',),
        ),
    ]
